management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  health:
    circuitbreakers:
      enabled: true

logging:
  level:
    root: INFO

resilience4j:
  circuitbreaker:
    instances:
      userServiceCall:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
  retry:
    instances:
      userServiceCall:
        max-attempts: 3
        wait-duration: 500ms
