spring.datasource.url=jdbc:postgresql://localhost:5432/jobapp_db
spring.datasource.username=postgres
spring.datasource.password=manager
spring.jpa.hibernate.ddl-auto=create-drop
jwt.secret=test-secret-key-for-unit-tests-only-32char
spring.cloud.vault.enabled=false
eureka.client.enabled=false
